r"""Machine learning the 2-D Ising transition, with physically generated label noise.

Classifying Monte Carlo spin configurations as "ordered" or "disordered" and
reading the critical temperature off the classifier is the standard machine-
learning approach to phases of matter (Carrasquilla & Melko, 2017). The ``q = 1``
arm below *is* that method: an MLP trained with ordinary cross-entropy.

What makes this a Tsallis problem is where the labels come from. They are
assigned by temperature, ``y = 1[T < T_c]``, but near the transition the
correlation length ``xi ~ |T - T_c|^{-1}`` exceeds the lattice, so a
configuration drawn just *above* ``T_c`` is genuinely typical of the ordered
phase. Its temperature label is then wrong -- this is **label noise generated by
the physics of finite-size crossover**, not injected by hand as in
``examples/classification.py``. And because it is physical, it is *measurable*
and it has a *knob*: ``eta_eff(T, L)`` is the error an optimal ``|m|``-threshold
classifier makes against the temperature labels, and it shrinks as ``L`` grows
and the crossover narrows.

That gives a sharper question than "is Tsallis better": the bounded Tsallis
cross-entropy (``q < 1``, per-example loss at most ``1/(1-q)``) should help in
proportion to how much of this noise there is, and the lattice size sets that.

What the run measures, scored against the order parameter rather than against the
temperature labels (the physical analogue of a clean test set), is a **threshold
rather than a smooth trend**. Where the pooled noise exceeds roughly 13 %
(``L <= 10``), ``q = 0.4`` and the learnable ``q`` gain about one accuracy point
over ``q = 1``, several standard errors clear. Where it falls below roughly 11 %
(``L >= 12``), they *cost* about the same. So nonextensivity pays here only above
a measurable value of a physical parameter -- and we report the sign change
rather than smoothing it over.

The learnable ``q`` is the arm that survives the regime change: it is at or near
the top in the noisy regime and the least penalized in the clean one. That is the
practical argument for treating ``q`` as a parameter to be learned rather than a
constant to be chosen, in a setting where the right value depends on a physical
scale the modeller does not control.

Every number is checked against something exact, so all of this is measurement
rather than claim:

- ``T_c = 2/ln(1+sqrt 2) = 2.2691853`` (Onsager, 1944), and the exact exponents
  ``nu = 1``, ``beta = 1/8``, ``u(T_c) = -sqrt 2 J``.
- The sampler is validated against Onsager's ``m(T)`` and against exhaustive
  enumeration of all ``2**16`` states at ``L = 4``.
- Two *non*-machine-learning physics baselines locate ``T_c`` for comparison:
  the Binder-cumulant crossing and the ``<|m|>`` inflection point.
- Two *label-free* indicators answer the objection that the labels already encode
  ``T_c``: the Tsallis entropy of the network's output, whose peak needs no
  ``T_c``, and learning by confusion (van Nieuwenburg et al., 2017), which scans
  a *proposed* boundary and never sees the true one.

Run with: ``uv run python examples/ising_phases.py``
Add ``--full`` (or set ``QJAX_FULL=1``) for the large-lattice configuration.
"""

from __future__ import annotations

import os
import sys
from functools import partial
from pathlib import Path

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np

import qjax
import qjax.physics as qp
from qjax.nn import bounded_q, tsallis_cross_entropy_loss
from qjax.plots import CMAP, qcolors, qlinestyles, save_figure, use_qjax_style

FIG_DIR = Path(__file__).parent / "figures"

# (label, q_fixed, is_learnable). q = 1 is exactly the Carrasquilla-Melko setup.
BASELINE = "BGS (q = 1)"
METHODS = (
    (BASELINE, 1.0, False),
    ("Tsallis q = 0.7", 0.7, False),
    ("Tsallis q = 0.4", 0.4, False),
    ("learnable q", 0.0, True),
)
INDICATOR = "Tsallis q = 0.4"  # arm whose output supplies the label-free indicators

# Learnable-q range, matching examples/classification.py: it spans the robust
# (q < 1) and standard (q = 1) regimes and starts inside the robust one, since
# starting near q = 1 lets the network fit the contested band before q descends.
Q_MIN, Q_MAX, Q_RAW_INIT = 0.3, 1.3, -1.4  # init q ~ 0.50

HIDDEN = (64, 64)
LR = 3e-3
CONFUSION_METHODS = ((BASELINE, 1.0), ("Tsallis q = 0.4", 0.4))

# The two non-ML physics baselines are read inside the dense part of the
# temperature grid. This window contains the exact T_c, so those two estimators
# are told roughly where to look; it is applied to them and not to the learned
# estimators because restricting them *helps* them -- a noisy Binder curve
# crosses many times far from T_c -- which keeps the comparison conservative
# rather than flattering to the Tsallis arms. The confusion scan and the
# classifier crossings see the whole grid. Stated in the docs page too.
CRITICAL_WINDOW = (2.00, 2.62)

# Panel (a) shows one configuration from each phase and one at criticality.
SHOWCASE_TEMPERATURES = (1.5, qp.ISING_TC, 3.2)


def _temperature_grid(low: int, middle: int, high: int) -> jnp.ndarray:
    """A grid that is dense through the critical region and sparse outside it."""
    return jnp.concatenate(
        [
            jnp.linspace(1.20, 1.95, low),
            jnp.linspace(2.02, 2.58, middle),
            jnp.linspace(2.70, 3.60, high),
        ]
    )


def configuration(*, quick: bool, full: bool) -> dict:
    """Sizes, sweeps and seeds for the requested tier.

    ``quick`` is the smoke-test tier used by ``tests/``; ``full`` is the
    large-lattice run. Only counts change between tiers -- never the arms, never
    the physics -- so a claim measured at one tier means the same at another.
    """
    if quick:
        return {
            "sizes": (6, 8),
            "temperatures": _temperature_grid(4, 7, 3),
            "samples_per_temperature": 24,
            "equilibration": {6: 60, 8: 60},
            "steps": 200,
            "seeds": (0,),
            "confusion_boundaries": 5,
        }
    if full:
        return {
            "sizes": (8, 12, 16, 24, 32, 48, 64),
            "temperatures": _temperature_grid(10, 25, 12),
            "samples_per_temperature": 400,
            "equilibration": {8: 800, 12: 1200, 16: 1500, 24: 3000, 32: 5000, 48: 9000, 64: 14000},
            "steps": 2500,
            "seeds": (0, 1, 2, 3, 4, 5, 6, 7),
            "confusion_boundaries": 17,
        }
    return {
        "sizes": (8, 10, 12, 16),
        "temperatures": _temperature_grid(7, 15, 8),
        "samples_per_temperature": 80,
        "equilibration": {8: 400, 10: 400, 12: 500, 16: 700},
        "steps": 700,
        "seeds": (0, 1, 2, 3),
        "confusion_boundaries": 9,
    }


# --------------------------------------------------------------------------- #
# The physically generated label noise, and the labels a perfect model would use
# --------------------------------------------------------------------------- #
def order_parameter_reference(configurations: jnp.ndarray, temperatures: jnp.ndarray):
    """Best ``|m|``-threshold classifier: its threshold, its per-``T`` error, its labels.

    The magnetization is the exact order parameter, so a threshold on ``|m|`` is
    the best any function of the configuration can do at separating the phases.
    Two things follow, and they are the two ingredients of this example:

    - Where the threshold classifier disagrees with the temperature label, the
      *label* is what is wrong. Its per-temperature error rate ``eta_eff(T, L)``
      is therefore a measurement of the physically generated label noise, and it
      plays the role that the injected ``eta`` plays in
      ``examples/classification.py``.
    - Its own labels are the closest thing to ground truth available, so scoring
      a network against them is the analogue of a *clean* test set. Scoring
      against the temperature labels instead rewards fitting the noise, which is
      exactly what the unbounded loss does.

    Args:
        configurations: Samples of shape ``(T, S, L, L)``.
        temperatures: The temperature grid, shape ``(T,)``.

    Returns:
        ``(threshold, noise, labels)`` with ``noise`` of shape ``(T,)`` and
        ``labels`` of shape ``(T, S)``.
    """
    absolute = jnp.abs(qp.ising_magnetization(configurations))
    ordered = (temperatures < qp.ISING_TC)[:, None]

    candidates = jnp.linspace(0.0, 1.0, 201)[:, None, None]
    pooled = jnp.mean((absolute[None, :, :] > candidates) != ordered[None, :, :], axis=(1, 2))
    threshold = candidates[jnp.argmin(pooled), 0, 0]

    predicted = absolute > threshold
    return threshold, jnp.mean(predicted != ordered, axis=-1), predicted.astype(jnp.int32)


# --------------------------------------------------------------------------- #
# The classifier
# --------------------------------------------------------------------------- #
def init_params(key: jax.Array, num_sites: int) -> dict:
    """Initialize a ``num_sites -> HIDDEN -> 2`` MLP, plus the learnable ``q_raw``."""
    k1, k2, k3 = jax.random.split(key, 3)
    h1, h2 = HIDDEN
    return {
        "w1": jax.random.normal(k1, (num_sites, h1)) * jnp.sqrt(2.0 / num_sites),
        "b1": jnp.zeros(h1),
        "w2": jax.random.normal(k2, (h1, h2)) * jnp.sqrt(2.0 / h1),
        "b2": jnp.zeros(h2),
        "w3": jax.random.normal(k3, (h2, 2)) * jnp.sqrt(2.0 / h2),
        "b3": jnp.zeros(2),
        "q_raw": jnp.array(Q_RAW_INIT),
    }


def logits(params: dict, x: jnp.ndarray) -> jnp.ndarray:
    """Forward pass returning two logits: [disordered, ordered]."""
    h = jnp.tanh(x @ params["w1"] + params["b1"])
    h = jnp.tanh(h @ params["w2"] + params["b2"])
    return h @ params["w3"] + params["b3"]


def resolve_q(params: dict, q_fixed: float, is_learnable: bool):
    """The entropic index in use: a constant, or the bounded learnable one."""
    return bounded_q(params["q_raw"], Q_MIN, Q_MAX) if is_learnable else q_fixed


@partial(jax.jit, static_argnames=("is_learnable", "steps"))
def train(params: dict, x, y_onehot, q_fixed, is_learnable: bool, steps: int):
    """Full-batch Adam on the Tsallis cross-entropy; returns params and the q trace.

    ``normalizer_q=1.0`` keeps an ordinary softmax under the deformed loss. That
    is deliberate twice over: it avoids the 50-step entmax bisection in the inner
    loop, and it rules out the ``+inf`` the loss docstring warns about, where a
    sparse normalizer puts exactly zero mass on the true class.
    """
    b1, b2, eps = 0.9, 0.999, 1e-8
    m = jax.tree_util.tree_map(jnp.zeros_like, params)
    v = jax.tree_util.tree_map(jnp.zeros_like, params)

    def loss_fn(p):
        q = resolve_q(p, q_fixed, is_learnable)
        return tsallis_cross_entropy_loss(
            logits(p, x), y_onehot, q=q, from_logits=True, normalizer_q=1.0
        )

    def step(carry, t):
        p, m, v = carry
        grads = jax.grad(loss_fn)(p)
        m = jax.tree_util.tree_map(lambda m, g: b1 * m + (1 - b1) * g, m, grads)
        v = jax.tree_util.tree_map(lambda v, g: b2 * v + (1 - b2) * g * g, v, grads)
        bc1, bc2 = 1 - b1 ** (t + 1), 1 - b2 ** (t + 1)
        p = jax.tree_util.tree_map(
            lambda p, m, v: p - LR * (m / bc1) / (jnp.sqrt(v / bc2) + eps), p, m, v
        )
        return (p, m, v), resolve_q(p, q_fixed, is_learnable)

    (params, _, _), trace = jax.lax.scan(step, (params, m, v), jnp.arange(steps))
    return params, trace


def flatten_symmetrized(configurations: jnp.ndarray, labels: jnp.ndarray):
    """Flatten to ``(N, L*L)`` and append the global spin flip of every sample.

    Not data augmentation for its own sake: ``-s`` has exactly the same energy as
    ``s``, so without it the network can key on ``sign(m)``, which carries no
    phase information at all.
    """
    x = configurations.reshape(-1, configurations.shape[-1] * configurations.shape[-2])
    y = labels.reshape(-1)
    return jnp.concatenate([x, -x]), jnp.concatenate([y, y])


def temperature_labels(temperatures: jnp.ndarray, samples: int, boundary: float) -> jnp.ndarray:
    """``1[T < boundary]``, broadcast to one label per sample."""
    return jnp.repeat((temperatures < boundary).astype(jnp.int32)[:, None], samples, axis=1)


def balanced_accuracy(predicted: jnp.ndarray, targets: jnp.ndarray) -> float:
    """Mean of the two per-class recalls.

    Plain accuracy is the wrong metric for the confusion scan: a proposed
    boundary near the edge of the temperature grid puts almost every sample in
    one class, and a constant predictor then scores close to 1. That trivial rise
    is what produces the outer arms of the W and can swamp the real peak.
    Averaging the per-class recalls pins an uninformative boundary at 0.5, so the
    only way to score well is to separate two populations that genuinely differ.
    """
    recalls = [
        jnp.mean(predicted[targets == label] == label)
        for label in (0, 1)
        if int(jnp.sum(targets == label)) > 0
    ]
    return float(jnp.mean(jnp.stack(recalls)))


def _windowed(temperatures: jnp.ndarray, curve: jnp.ndarray):
    """Restrict a curve to `CRITICAL_WINDOW`, where the temperature grid is dense."""
    inside = (temperatures >= CRITICAL_WINDOW[0]) & (temperatures <= CRITICAL_WINDOW[1])
    return temperatures[inside], curve[inside]


def ordered_probability(params: dict, configurations: jnp.ndarray):
    """Mean ``P(ordered)`` and mean output Tsallis entropy at each temperature.

    The entropy is evaluated at ``q = 2`` -- the Gini/collision index, whose
    ``q -> 1`` limit is the Shannon entropy. It peaks where the network is
    maximally undecided, so its maximum is a pseudo-critical temperature obtained
    *without* reference to ``T_c``.
    """
    flat = configurations.reshape(*configurations.shape[:2], -1)
    symmetric = jnp.concatenate([flat, -flat], axis=1)
    probabilities = jax.nn.softmax(logits(params, symmetric), axis=-1)
    entropy = qjax.tsallis_entropy(probabilities, q=2.0, axis=-1)
    return jnp.mean(probabilities[..., 1], axis=-1), jnp.mean(entropy, axis=-1)


def crossover_width(temperatures: jnp.ndarray, probability: jnp.ndarray) -> jnp.ndarray:
    r"""Temperature interval over which ``P(ordered)`` falls from 3/4 to 1/4.

    This is the width of the region the classifier cannot decide, so it is set by
    where ``xi`` exceeds ``L`` and scales as ``L^{-1/nu}``. Reading ``nu`` off it
    is the cleanest exponent measurement in the pipeline -- and, unlike the
    ``T_c`` estimates, it needs no extrapolation.
    """
    upper = qp.crossing_temperature(temperatures, probability, 0.25)
    lower = qp.crossing_temperature(temperatures, probability, 0.75)
    return upper - lower


# --------------------------------------------------------------------------- #
# Experiment
# --------------------------------------------------------------------------- #
def run(config: dict) -> dict:
    """Sample, train every arm at every lattice size, and collect the estimates."""
    temperatures = config["temperatures"]
    sizes = config["sizes"]
    per_temperature = config["samples_per_temperature"]
    split = per_temperature - per_temperature // 2

    results: dict = {"temperatures": np.asarray(temperatures), "sizes": sizes, "showcase": {}}
    for field in (
        "noise",
        "bayes_error",
        "magnetization",
        "energy",
        "binder",
        "probability",
        "entropy",
        "width",
        "accuracy_temperature",
        "accuracy_order",
        "q_trace",
    ):
        results[field] = {}

    for size in sizes:
        print(f"  L = {size}: sampling", flush=True)
        configurations = qp.sample_ising(
            jax.random.PRNGKey(1000 + size),
            size,
            temperatures,
            per_temperature,
            config["equilibration"][size],
        )
        magnetization = qp.ising_magnetization(configurations)
        threshold, noise, clean_labels = order_parameter_reference(configurations, temperatures)

        results["magnetization"][size] = np.asarray(jnp.mean(jnp.abs(magnetization), axis=-1))
        results["energy"][size] = np.asarray(
            jnp.mean(qp.ising_energy(configurations), axis=-1) / size**2
        )
        results["binder"][size] = np.asarray(qp.binder_cumulant(magnetization, axis=-1))
        results["noise"][size] = np.asarray(noise)
        results["bayes_error"][size] = float(jnp.mean(noise))

        train_x, train_y = flatten_symmetrized(
            configurations[:, :split],
            temperature_labels(temperatures, split, qp.ISING_TC),
        )
        test_x, test_temperature = flatten_symmetrized(
            configurations[:, split:],
            temperature_labels(temperatures, per_temperature - split, qp.ISING_TC),
        )
        _, test_order = flatten_symmetrized(configurations[:, split:], clean_labels[:, split:])
        one_hot = jax.nn.one_hot(train_y, 2)

        for label, q_fixed, learnable in METHODS:
            gathered: dict[str, list] = {
                k: [] for k in ("prob", "entropy", "width", "temp", "order", "trace")
            }
            for seed in config["seeds"]:
                start = init_params(jax.random.PRNGKey(seed), size**2)
                trained, trace = train(start, train_x, one_hot, q_fixed, learnable, config["steps"])
                probability, entropy = ordered_probability(trained, configurations[:, split:])
                predicted = jnp.argmax(logits(trained, test_x), axis=-1)
                gathered["prob"].append(np.asarray(probability))
                gathered["entropy"].append(np.asarray(entropy))
                gathered["width"].append(float(crossover_width(temperatures, probability)))
                gathered["temp"].append(float(jnp.mean(predicted == test_temperature)))
                gathered["order"].append(float(jnp.mean(predicted == test_order)))
                gathered["trace"].append(np.asarray(trace))
            results["probability"][size, label] = np.stack(gathered["prob"])
            results["entropy"][size, label] = np.stack(gathered["entropy"])
            results["width"][size, label] = np.array(gathered["width"])
            results["accuracy_temperature"][size, label] = np.array(gathered["temp"])
            results["accuracy_order"][size, label] = np.array(gathered["order"])
            results["q_trace"][size, label] = np.stack(gathered["trace"])
            print(
                f"    {label:<16} accuracy: T-label {np.mean(gathered['temp']):.4f}"
                f"  order-parameter {np.mean(gathered['order']):.4f}"
                f"   final q {np.mean([t[-1] for t in gathered['trace']]):.3f}",
                flush=True,
            )

        print(
            f"    |m| threshold {float(threshold):.3f},"
            f" pooled label noise {results['bayes_error'][size]:.4f}",
            flush=True,
        )
        if size == sizes[-1]:
            for target in SHOWCASE_TEMPERATURES:
                index = int(jnp.argmin(jnp.abs(temperatures - target)))
                results["showcase"][target] = (
                    np.asarray(configurations[index, 0]),
                    float(jnp.abs(magnetization[index, 0])),
                    float(temperatures[index]),
                )
    return results


def learning_by_confusion(config: dict) -> dict:
    """Scan a *proposed* phase boundary; balanced accuracy peaks at the real one.

    The pipeline never sees ``T_c``: for each candidate ``T'`` the labels are
    ``1[T < T']``, the network is retrained, and its balanced test accuracy is
    recorded. A wrong boundary is inconsistent with the data on both sides, so the
    curve peaks at the true transition. This is the answer to "your labels already
    contain the answer".
    """
    size = config["sizes"][-1]
    temperatures = config["temperatures"]
    per_temperature = config["samples_per_temperature"]
    split = per_temperature - per_temperature // 2
    boundaries = np.linspace(2.0, 2.6, config["confusion_boundaries"])

    configurations = qp.sample_ising(
        jax.random.PRNGKey(1000 + size),
        size,
        temperatures,
        per_temperature,
        config["equilibration"][size],
    )
    steps = max(config["steps"] // 2, 100)

    curves = {}
    for label, q_fixed in CONFUSION_METHODS:
        accuracies = []
        for boundary in boundaries:
            train_x, train_y = flatten_symmetrized(
                configurations[:, :split], temperature_labels(temperatures, split, float(boundary))
            )
            test_x, test_y = flatten_symmetrized(
                configurations[:, split:],
                temperature_labels(temperatures, per_temperature - split, float(boundary)),
            )
            trained, _ = train(
                init_params(jax.random.PRNGKey(0), size**2),
                train_x,
                jax.nn.one_hot(train_y, 2),
                q_fixed,
                False,
                steps,
            )
            accuracies.append(
                balanced_accuracy(jnp.argmax(logits(trained, test_x), axis=-1), test_y)
            )
        curves[label] = np.array(accuracies)
        peak = float(qp.peak_temperature(jnp.asarray(boundaries), jnp.asarray(accuracies)))
        print(f"    confusion {label:<16} peak at T' = {peak:.4f}")
    return {"boundaries": boundaries, "curves": curves, "size": size}


# --------------------------------------------------------------------------- #
# Estimates of T_c and of the exponents
# --------------------------------------------------------------------------- #
def _crossings(results: dict, label: str, seed: int) -> jnp.ndarray:
    """Per-size temperature at which one seed's ``P(ordered)`` crosses 1/2."""
    temperatures = jnp.asarray(results["temperatures"])
    return jnp.array(
        [
            qp.crossing_temperature(temperatures, results["probability"][size, label][seed])
            for size in results["sizes"]
        ]
    )


def estimate_critical_temperatures(results: dict, confusion: dict) -> dict:
    """Every estimator's ``T_c``, with a seed standard error where one exists."""
    temperatures = jnp.asarray(results["temperatures"])
    sizes = jnp.asarray(results["sizes"], dtype=float)
    num_seeds = results["probability"][results["sizes"][0], BASELINE].shape[0]
    estimates: dict = {}

    def summarize(values: list[float]) -> tuple[float, float]:
        return float(np.mean(values)), float(np.std(values) / np.sqrt(max(len(values), 1)))

    for label, _, _ in METHODS:
        extrapolated, largest = [], []
        for seed in range(num_seeds):
            crossings = _crossings(results, label, seed)
            extrapolated.append(
                float(qp.finite_size_extrapolation(sizes, crossings, qp.ISING_NU)[0])
            )
            largest.append(float(crossings[-1]))
        estimates[f"{label}, $1/L \\to 0$"] = summarize(extrapolated)
        estimates[f"{label}, largest $L$"] = summarize(largest)

    # Label-free arm 1: the peak of the output Tsallis entropy, same extrapolation.
    peaks = []
    for seed in range(num_seeds):
        per_size = jnp.array(
            [
                qp.peak_temperature(temperatures, results["entropy"][size, INDICATOR][seed])
                for size in results["sizes"]
            ]
        )
        peaks.append(float(qp.finite_size_extrapolation(sizes, per_size, qp.ISING_NU)[0]))
    estimates["$S_q$ peak (label-free)"] = summarize(peaks)

    # Label-free arm 2: the confusion peak, refined parabolically.
    estimates["confusion peak (label-free)"] = (
        float(
            qp.peak_temperature(
                jnp.asarray(confusion["boundaries"]), jnp.asarray(confusion["curves"][INDICATOR])
            )
        ),
        0.0,
    )

    # Physics baseline 1: Binder-cumulant crossings against the smallest lattice.
    reference = jnp.asarray(results["binder"][results["sizes"][0]])
    crossings = jnp.array(
        [
            qp.crossing_temperature(
                *_windowed(temperatures, jnp.asarray(results["binder"][size]) - reference), 0.0
            )
            for size in results["sizes"][1:]
        ]
    )
    finite = crossings[jnp.isfinite(crossings)]
    estimates["Binder crossing (physics)"] = (float(jnp.mean(finite)), float(jnp.std(finite)))

    # Physics baseline 2: the inflection point of <|m|>(T).
    midpoints = 0.5 * (temperatures[1:] + temperatures[:-1])
    slopes = jnp.array(
        [
            qp.peak_temperature(
                *_windowed(
                    midpoints,
                    -jnp.diff(jnp.asarray(results["magnetization"][size])) / jnp.diff(temperatures),
                )
            )
            for size in results["sizes"]
        ]
    )
    estimates["$|m|$ inflection (physics)"] = (
        float(qp.finite_size_extrapolation(sizes, slopes, qp.ISING_NU)[0]),
        0.0,
    )
    return estimates


def critical_exponents(results: dict) -> dict:
    r"""Recover ``nu`` from the classifier's crossover width and ``beta`` from ``<|m|>``."""
    temperatures = jnp.asarray(results["temperatures"])
    sizes = jnp.asarray(results["sizes"], dtype=float)

    widths = jnp.array(
        [float(np.mean(results["width"][size, BASELINE])) for size in results["sizes"]]
    )
    # w(L) ~ L^{-1/nu}, so the log-log slope is -1/nu.
    slope, _, stderr = qp.fit_power_law(sizes, widths)
    nu = float(-1.0 / slope)

    # Right at T_c, <|m|> ~ L^{-beta/nu}: read beta off the size dependence.
    index = int(jnp.argmin(jnp.abs(temperatures - qp.ISING_TC)))
    at_criticality = jnp.array([results["magnetization"][size][index] for size in results["sizes"]])
    magnetization_slope, _, magnetization_error = qp.fit_power_law(sizes, at_criticality)
    return {
        "nu": (nu, float(stderr / slope**2)),
        "beta": (
            float(-magnetization_slope * qp.ISING_NU),
            float(magnetization_error * qp.ISING_NU),
        ),
        "widths": np.asarray(widths),
    }


# --------------------------------------------------------------------------- #
# Figures
# --------------------------------------------------------------------------- #
def plot_main(results: dict, exponents: dict, path: Path) -> None:
    """Configurations, sampler validation, the measured noise, and what q buys."""
    temperatures = results["temperatures"]
    sizes = results["sizes"]
    size_colors = qcolors(len(sizes))
    method_colors = qcolors(len(METHODS))
    method_styles = qlinestyles(len(METHODS))

    fig = plt.figure(figsize=(13.2, 7.6))
    grid = fig.add_gridspec(2, 3, hspace=0.36, wspace=0.30)

    # (a) three configurations spanning the transition.
    inner = grid[0, 0].subgridspec(1, 3, wspace=0.08)
    for column, target in enumerate(SHOWCASE_TEMPERATURES):
        spins, absolute, actual = results["showcase"][target]
        ax = fig.add_subplot(inner[0, column])
        ax.imshow(spins, cmap=CMAP, vmin=-1, vmax=1, interpolation="nearest")
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(f"$T={actual:.2f}$\n$|m|={absolute:.2f}$", fontsize=8.5, pad=3)
        if column == 1:
            ax.set_xlabel(f"(a)  $L={sizes[-1]}$ configurations", fontsize=9.5, labelpad=4)

    # (b) sampler validation against Onsager and the exact L = 4 enumeration.
    ax = fig.add_subplot(grid[0, 1])
    fine = np.linspace(temperatures.min(), qp.ISING_TC, 300)
    ax.plot(
        fine,
        np.asarray(qp.onsager_magnetization(jnp.asarray(fine))),
        color="0.25",
        lw=1.2,
        ls="--",
        label=r"Onsager $m(T)$, $L\to\infty$",
    )
    for color, size in zip(size_colors, sizes, strict=True):
        ax.plot(
            temperatures, results["magnetization"][size], color=color, lw=1.3, label=f"$L={size}$"
        )
    # The L = 4 pair is the actual validation: a sampled curve on top of the
    # exhaustive enumeration of all 2**16 states, at the same lattice size.
    exact = jax.vmap(lambda t: qp.ising_exact_observables(4, t)["abs_magnetization"])(
        jnp.asarray(temperatures)
    )
    sampled = qp.sample_ising(jax.random.PRNGKey(4), 4, jnp.asarray(temperatures), 2000, 200)
    ax.plot(
        temperatures,
        np.asarray(jnp.mean(jnp.abs(qp.ising_magnetization(sampled)), axis=-1)),
        color="0.45",
        lw=1.0,
        label="sampled $L=4$",
    )
    ax.plot(
        temperatures,
        np.asarray(exact),
        ls="none",
        marker="o",
        ms=3.2,
        mfc="none",
        mew=0.8,
        color="0.15",
        label=r"exact $L=4$ ($2^{16}$ states)",
    )
    ax.axvline(qp.ISING_TC, color="0.55", lw=0.9, ls=":")
    ax.set_xlabel("temperature $T$")
    ax.set_ylabel(r"$\langle |m| \rangle$")
    ax.set_title("(b) sampler vs. exact", fontsize=10)
    ax.legend(fontsize=7.4, ncols=2, loc="lower left")

    # (c) the measured, physically generated label noise.
    ax = fig.add_subplot(grid[0, 2])
    for color, size in zip(size_colors, sizes, strict=True):
        ax.plot(
            temperatures,
            results["noise"][size],
            color=color,
            lw=1.4,
            label=rf"$L={size}$  ($\bar\eta={results['bayes_error'][size]:.3f}$)",
        )
    ax.axvline(qp.ISING_TC, color="0.55", lw=0.9, ls=":")
    ax.set_xlabel("temperature $T$")
    ax.set_ylabel(r"$\eta_{\rm eff}(T, L)$")
    ax.set_title("(c) label noise from finite-size crossover", fontsize=10)
    ax.legend(fontsize=7.4)

    # (d) P(ordered) per arm at the largest lattice.
    ax = fig.add_subplot(grid[1, 0])
    largest = sizes[-1]
    for color, style, (label, _, _) in zip(method_colors, method_styles, METHODS, strict=True):
        curves = results["probability"][largest, label]
        mean = curves.mean(axis=0)
        ax.plot(temperatures, mean, color=color, ls=style, lw=1.5, label=label)
        if curves.shape[0] > 1:
            spread = curves.std(axis=0) / np.sqrt(curves.shape[0])
            ax.fill_between(
                temperatures, mean - spread, mean + spread, color=color, alpha=0.18, lw=0
            )
    ax.axhline(0.5, color="0.55", lw=0.8)
    ax.axvline(qp.ISING_TC, color="0.25", lw=1.0, ls="--", label="exact $T_c$")
    ax.set_xlabel("temperature $T$")
    ax.set_ylabel(r"$\langle P(\mathrm{ordered}) \rangle$")
    ax.set_title(f"(d) classifier output, $L={largest}$", fontsize=10)
    ax.legend(fontsize=8)

    # (e) finite-size extrapolation of the 1/2 crossing.
    ax = fig.add_subplot(grid[1, 1])
    inverse = 1.0 / np.asarray(sizes, dtype=float)
    for color, style, (label, _, _) in zip(method_colors, method_styles, METHODS, strict=True):
        crossings = np.array(
            [
                float(
                    qp.crossing_temperature(
                        jnp.asarray(temperatures),
                        jnp.asarray(results["probability"][size, label].mean(axis=0)),
                    )
                )
                for size in sizes
            ]
        )
        intercept, slope, _ = qp.finite_size_extrapolation(
            jnp.asarray(sizes, dtype=float), jnp.asarray(crossings), qp.ISING_NU
        )
        ax.plot(inverse, crossings, ls="none", marker="o", ms=4.5, color=color)
        span = np.linspace(0.0, inverse.max() * 1.05, 20)
        ax.plot(
            span,
            float(intercept) + float(slope) * span,
            color=color,
            ls=style,
            lw=1.3,
            label=f"{label}: {float(intercept):.4f}",
        )
    ax.axhline(qp.ISING_TC, color="0.25", lw=1.0, ls="--")
    ax.text(
        0.02,
        qp.ISING_TC,
        f"  exact {qp.ISING_TC:.4f}",
        va="bottom",
        ha="left",
        fontsize=8,
        color="0.25",
        transform=ax.get_yaxis_transform(),
    )
    ax.set_xlabel("$1/L$")
    ax.set_ylabel(r"$T_c(L)$")
    ax.set_title(r"(e) extrapolation with exact $\nu = 1$", fontsize=10)
    largest_crossing = float(
        qp.crossing_temperature(
            jnp.asarray(temperatures),
            jnp.asarray(results["probability"][sizes[-1], BASELINE].mean(axis=0)),
        )
    )
    ax.annotate(
        f"crossing at $L={sizes[-1]}$: {largest_crossing:.4f}\n"
        r"(the $1/L$ fit curves at small $L$)",
        (0.03, 0.03),
        xycoords="axes fraction",
        fontsize=7.2,
        color="0.3",
    )
    ax.legend(fontsize=7.6, loc="upper right")

    # (f) the Tsallis result: the gain tracks the physically generated noise.
    ax = fig.add_subplot(grid[1, 2])
    noise = np.array([results["bayes_error"][size] for size in sizes])
    baseline = np.array([results["accuracy_order"][size, BASELINE].mean() for size in sizes])
    for color, style, (label, _, _) in zip(method_colors, method_styles, METHODS, strict=True):
        if label == BASELINE:
            continue
        arm = np.array([results["accuracy_order"][size, label] for size in sizes])
        gain = 100.0 * (arm.mean(axis=1) - baseline)
        spread = 100.0 * arm.std(axis=1) / np.sqrt(arm.shape[1])
        ax.errorbar(
            noise,
            gain,
            yerr=spread,
            color=color,
            ls=style,
            lw=1.5,
            marker="o",
            ms=4.5,
            capsize=2,
            label=label,
        )
    ax.axhline(0.0, color="0.25", lw=1.0, ls="--")
    margin = 0.06 * (noise.max() - noise.min())
    ax.set_xlim(noise.min() - margin, noise.max() + margin)
    top = ax.get_ylim()[1]
    for x, size in zip(noise, sizes, strict=True):
        ax.annotate(f"$L={size}$", (x, top), fontsize=7, ha="center", va="top", color="0.35")
    ax.set_xlabel(r"pooled label noise $\bar\eta(L)$")
    ax.set_ylabel("order-parameter accuracy\ngain over BGS (points)")
    ax.set_title(r"(f) what $q<1$ buys, vs. how much noise there is", fontsize=10)
    ax.legend(fontsize=7.6, loc="upper left")

    save_figure(fig, path)
    plt.close(fig)


def plot_scaling(results: dict, exponents: dict, estimates: dict, confusion: dict, path: Path):
    """Binder, the FSS collapse, the confusion scan, and the ``T_c`` scoreboard."""
    temperatures = results["temperatures"]
    sizes = results["sizes"]
    size_colors = qcolors(len(sizes))

    fig, axes = plt.subplots(2, 2, figsize=(11.8, 8.4))
    fig.subplots_adjust(hspace=0.34, wspace=0.40)

    # (a) Binder cumulant: curves for different L cross at T_c.
    ax = axes[0, 0]
    for color, size in zip(size_colors, sizes, strict=True):
        ax.plot(temperatures, results["binder"][size], color=color, lw=1.4, label=f"$L={size}$")
    ax.axvline(qp.ISING_TC, color="0.25", lw=1.0, ls="--", label="exact $T_c$")
    ax.axhline(2.0 / 3.0, color="0.6", lw=0.7, ls=":")
    ax.set_xlabel("temperature $T$")
    ax.set_ylabel(r"$U_4$")
    ax.set_title("(a) Binder cumulant (no machine learning)", fontsize=10)
    ax.legend(fontsize=8, loc="lower left")

    # (b) FSS collapse with the exact exponents: a strong equilibration check.
    ax = axes[0, 1]
    for color, size in zip(size_colors, sizes, strict=True):
        scaled_x = (temperatures - qp.ISING_TC) * size ** (1.0 / qp.ISING_NU)
        scaled_y = results["magnetization"][size] * size ** (qp.ISING_BETA_EXP / qp.ISING_NU)
        ax.plot(scaled_x, scaled_y, color=color, lw=1.3, marker="o", ms=2.5, label=f"$L={size}$")
    ax.set_xlim(-25.0, 25.0)
    ax.set_xlabel(r"$(T - T_c)\,L^{1/\nu}$")
    ax.set_ylabel(r"$\langle |m| \rangle\, L^{\beta/\nu}$")
    ax.set_title(r"(b) collapse at exact $\beta=1/8$, $\nu=1$", fontsize=10)
    ax.legend(fontsize=8)

    # Inset: nu from the classifier's own crossover width, no extrapolation.
    widths = exponents["widths"]
    inset = ax.inset_axes((0.09, 0.11, 0.33, 0.30))
    inset.loglog(sizes, widths, "o", ms=3.5, color=size_colors[-1])
    fitted = np.asarray(sizes, dtype=float)
    nu = exponents["nu"][0]
    inset.loglog(fitted, widths[0] * (fitted / fitted[0]) ** (-1.0 / nu), lw=1.0, color="0.35")
    inset.set_title(rf"$w \sim L^{{-1/\nu}}$: $\nu={nu:.2f}$", fontsize=7, pad=2)
    inset.set_xlabel("$L$", fontsize=6.5, labelpad=0)
    inset.set_ylabel("$w$", fontsize=6.5, labelpad=0)
    inset.tick_params(labelsize=5.5, which="both")
    inset.grid(visible=False)

    # (c) learning by confusion: the peak needs no knowledge of T_c.
    ax = axes[1, 0]
    for color, (label, _) in zip(qcolors(len(CONFUSION_METHODS)), CONFUSION_METHODS, strict=True):
        curve = confusion["curves"][label]
        ax.plot(confusion["boundaries"], curve, color=color, lw=1.5, marker="o", ms=4, label=label)
        ax.axvline(
            float(qp.peak_temperature(jnp.asarray(confusion["boundaries"]), jnp.asarray(curve))),
            color=color,
            lw=0.8,
            ls=":",
        )
    ax.axvline(qp.ISING_TC, color="0.25", lw=1.0, ls="--", label="exact $T_c$")
    ax.set_xlabel(r"proposed boundary $T'$")
    ax.set_ylabel("balanced test accuracy")
    ax.set_title(f"(c) learning by confusion, $L={confusion['size']}$", fontsize=10)
    ax.legend(fontsize=8)

    # (d) the scoreboard: |T_c estimate - exact| for every estimator.
    ax = axes[1, 1]
    keys = sorted(estimates, key=lambda k: abs(estimates[k][0] - qp.ISING_TC), reverse=True)
    errors = [abs(estimates[k][0] - qp.ISING_TC) for k in keys]
    spreads = [estimates[k][1] for k in keys]
    positions = np.arange(len(keys))
    colors = [
        "#1a759f" if "physics" in k else "#52b69a" if "free" in k else "#168aad" for k in keys
    ]
    ax.barh(positions, errors, xerr=spreads, color=colors, height=0.66, error_kw={"lw": 0.9})
    for y, (error, key) in enumerate(zip(errors, keys, strict=True)):
        ax.text(error + max(errors) * 0.02, y, f"{estimates[key][0]:.4f}", va="center", fontsize=7)
    ax.set_yticks(positions)
    ax.set_yticklabels(keys, fontsize=7.4)
    ax.set_xlabel(r"$|T_c^{\rm est} - 2.269185|$")
    ax.set_title("(d) distance from the exact $T_c$", fontsize=10)
    ax.grid(axis="y", visible=False)

    save_figure(fig, path)
    plt.close(fig)


# --------------------------------------------------------------------------- #
def report(results: dict, estimates: dict, exponents: dict) -> None:
    """Print the validation table the docs page reproduces."""
    temperatures = jnp.asarray(results["temperatures"])
    index = int(jnp.argmin(jnp.abs(temperatures - qp.ISING_TC)))
    largest = results["sizes"][-1]
    best = min(estimates.items(), key=lambda kv: abs(kv[1][0] - qp.ISING_TC))

    print("\n  validation")
    print(f"    {'quantity':<40}{'measured':>13}{'exact':>13}")
    rows = (
        (f"T_c, best estimator ({best[0]})", best[1][0], qp.ISING_TC),
        ("nu, from the crossover width w(L)", exponents["nu"][0], qp.ISING_NU),
        ("beta, from <|m|>(T_c) vs L", exponents["beta"][0], qp.ISING_BETA_EXP),
        (f"u(T_c)/J at L = {largest}", results["energy"][largest][index], qp.ISING_ENERGY_AT_TC),
    )
    for name, measured, exact in rows:
        print(f"    {name:<40}{measured:>13.6f}{exact:>13.6f}")

    print("\n    T_c estimates, closest first")
    for label, (value, spread) in sorted(
        estimates.items(), key=lambda kv: abs(kv[1][0] - qp.ISING_TC)
    ):
        plain = label.replace("$", "").replace("\\to", "->").replace("\\", "")
        print(
            f"      {plain:<32}{value:.4f} +- {spread:.4f}   (error {abs(value - qp.ISING_TC):.4f})"
        )

    seeds = results["accuracy_order"][results["sizes"][0], BASELINE].size
    print("\n    order-parameter accuracy (the clean metric), by lattice size")
    for size in results["sizes"]:
        baseline = 100.0 * results["accuracy_order"][size, BASELINE].mean()
        spread = 100.0 * results["accuracy_order"][size, BASELINE].std() / np.sqrt(seeds)
        gains = "  ".join(
            f"{label}: {100.0 * results['accuracy_order'][size, label].mean() - baseline:+.2f}"
            f" +- {100.0 * results['accuracy_order'][size, label].std() / np.sqrt(seeds):.2f}"
            for label, _, _ in METHODS
            if label != BASELINE
        )
        print(
            f"      L = {size:<3} noise {results['bayes_error'][size]:.4f}"
            f"   BGS {baseline:.2f} +- {spread:.2f}   gain in points -- {gains}"
        )


def main(*, quick: bool = False, full: bool = False) -> None:
    """Run the experiment and write both figures."""
    use_qjax_style()
    config = configuration(quick=quick, full=full)
    grid = len(config["temperatures"])
    print(f"Ising phase classification: L in {config['sizes']}, {grid} temperatures")
    results = run(config)
    print("  learning by confusion")
    confusion = learning_by_confusion(config)
    estimates = estimate_critical_temperatures(results, confusion)
    exponents = critical_exponents(results)
    report(results, estimates, exponents)
    plot_main(results, exponents, FIG_DIR / "ising_phases")
    plot_scaling(results, exponents, estimates, confusion, FIG_DIR / "ising_phases_scaling")


if __name__ == "__main__":
    main(
        quick="--quick" in sys.argv,
        full="--full" in sys.argv or bool(os.environ.get("QJAX_FULL")),
    )
